parameters:
    logger_database.class: Tim\DataBundle\Handler\LoggerDatabaseHandler
    slider_info.class: Tim\DataBundle\Handler\SliderInfoHandler
    about.class: Tim\DataBundle\Handler\AboutHandler
    chef.class: Tim\DataBundle\Handler\ChefHandler

services:
#    tim_data.example:
#        class: Tim\DataBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    logger_database:
        class: '%logger_database.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]

    tim_data.slider_info_handler:
        class: '%slider_info.class%'
        arguments: ['@doctrine.orm.default_entity_manager']

    tim_data.about_handler:
        class: '%about.class%'
        arguments: ['@doctrine.orm.default_entity_manager']

    tim_data.chef_handler:
        class: '%chef.class%'
        arguments: ['@doctrine.orm.default_entity_manager']

    tim_data.about_item.service:
        class: Tim\DataBundle\Service\FileUploaderService
        arguments: ['%about_item_root_directory%', '%about_item_directory%']

    tim_data.about_item_upload_listener:
        class: Tim\DataBundle\EventListener\AboutItemUploadListener
        arguments: ['@tim_data.about_item.service']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.orm.event_listener, event: postLoad, method: postLoad }

    tim_data.blog_record.service:
        class: Tim\DataBundle\Service\FileUploaderService
        arguments: ['%blog_record_root_directory%', '%blog_record_directory%']

    tim_data.blog_record_upload_listener:
        class: Tim\DataBundle\EventListener\BlogRecordUploadListener
        arguments: ['@tim_data.blog_record.service']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.orm.event_listener, event: postLoad, method: postLoad }

    tim_data.chef.service:
        class: Tim\DataBundle\Service\FileUploaderService
        arguments: ['%chefs_root_directory%', '%chefs_directory%']

    tim_data.chef_upload_listener:
        class: Tim\DataBundle\EventListener\ChefUploadListener
        arguments: ['@tim_data.chef.service']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.orm.event_listener, event: postLoad, method: postLoad }

    tim_data.exception_listener:
        class: Tim\DataBundle\EventListener\ExceptionListener
        arguments: ['@doctrine.orm.default_entity_manager', '@security.token_storage']
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }