# Override User Admin class
parameters:
    sonata.user.admin.user.class: Tim\BackendBundle\Admin\UserAdmin
    sonata.user.admin.group.class: Tim\BackendBundle\Admin\BaseGroupAdmin

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: Tim\BackendBundle\Entity\User
        group: Tim\BackendBundle\Entity\BaseGroup
    admin:
        user:
            class: Tim\BackendBundle\Admin\UserAdmin
        group:
            class: Tim\BackendBundle\Admin\BaseGroupAdmin

sonata_admin:
    show_mosaic_button: false
    security:
        handler: sonata.admin.security.handler.role