parameters:
    security.authentication.success_handler.class: Tim\BackendBundle\Handler\AuthenticationSuccessHandler
    security.authentication.failure_handler.class: Tim\BackendBundle\Handler\AuthenticationFailureHandler
    tim_backend.service.user_service.class: Tim\BackendBundle\Service\UserService

services:
#    tim_backend.example:
#        class: Tim\BackendBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    tim_backend.listener.interactive_login_listener:
        class: Tim\BackendBundle\EventListener\LoginListener
        arguments: ['@tim_backend.service.user_service', '@request_stack']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    # authentication failure event listener
    tim_backend.listener.authentication_failure_event_listener:
        class: Tim\BackendBundle\EventListener\LoginListener
        arguments: ['@tim_backend.service.user_service', '@request_stack']
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }

    tim_backend.service.user_service:
        class: '%tim_backend.service.user_service.class%'
        arguments: ['@doctrine.orm.default_entity_manager']

    tim_backend.admin.logger:
        class: Tim\BackendBundle\Admin\LoggerAdmin
        arguments: [~, Tim\DataBundle\Entity\Logger, TimBackendBundle:LoggerAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'System', label: 'Log', icon: '<i class="fa fa-cogs"></i>' }

    tim_backend.admin.configuration:
        class: Tim\BackendBundle\Admin\ConfigurationAdmin
        arguments: [~, Tim\DataBundle\Entity\Configuration, TimBackendBundle:ConfigurationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'System', label: 'Configuration' }
