parameters:
    security.authentication.success_handler.class: Tim\BackendBundle\Handler\AuthenticationSuccessHandler
    security.authentication.failure_handler.class: Tim\BackendBundle\Handler\AuthenticationFailureHandler

services:
#    tim_backend.example:
#        class: Tim\BackendBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
