<?php

namespace Tim\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BaseGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseGroupRepository extends EntityRepository
{
}
