<?php

namespace Tim\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutRepository extends EntityRepository
{
    public function getListQuery()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->leftJoin('a.aboutItems', 'aboutItems')
            ->addSelect('aboutItems')
            ->leftJoin('a.blogRecord', 'blogRecord')
            ->addSelect('blogRecord')
        ;

        $qb->orderBy('a.updatedAt', 'ASC');

        return $qb;
    }
}
