<?php

namespace Tim\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRecordRepository extends EntityRepository
{
}
