<?php

namespace Tim\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefRepository extends EntityRepository
{
    public function getListQuery($limit = null)
    {
        $qb = $this->createQueryBuilder('c');

        if (null !== $limit && $limit > 0) {
            $qb->setMaxResults((int)$limit);
        }

        $qb->orderBy('c.updatedAt', 'ASC');

        return $qb;
    }

    public function getByIdQuery($id)
    {
        $qb = $this->createQueryBuilder('c');

        $qb->andWhere('c.id', ':id')
            ->setParameter('id', (int)$id)
        ;

        $qb->setMaxResults(1);

        return $qb;
    }
}
