<?php

namespace Tim\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyInfoRepository extends EntityRepository
{
}
