<?php

namespace Tim\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderInfoRepository extends EntityRepository
{
    public function getSliderInfoQuery($limit = null)
    {
        $qb = $this->createQueryBuilder('si');

        if (null !== $limit && $limit > 0) {
            $qb->setMaxResults((int)$limit);
        }

        $qb->orderBy('si.orderNumber', 'ASC');

        return $qb;
    }
}
